baseURL = 'https://ttanay.github.io/'
languageCode = 'en-us'
title = 'Tanay Tummalapalli'
theme = 'hugo-bearblog'
publishDir = 'docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true
  hideMadeWithLine = true
